#+title: Git, GitHub and Reproducible Research
#+author: Alexander E. Zarebski

* TODO Background material

** Disclaimer

These materials makes use of proprietary products and a simplified workflow in
order to emphasise the main concepts and to save on installation and
configuration time. Some references will be given at the end to direct you to
free and open source solutions and more sustainable workflows; the core ideas
are the same though.

** Version control (VC)

/Version control/ (VC) refers to systems which help to manage the writing and
maintenance of things such as software, documents, and websites. These systems
were developed to manage large software projects but are useful at many levels.
For example, VC can help you avoid the following situation: =my-analysis.R=,
=my-analysis-final.R=, =my-analysis-final-again.R=, and so on. Try coming back to
that 3 months later when a reviewer asks you to re-run something with a slight
modification!

*** Reproducible research and Open research

In addition to helping *you* with organising your files, a VC system and it's
associated tooling can also help the scientific community by helping to make
your research reproducible and open.

For your computational research to be considered /reproducible,/ it needs to be
described in such a way that others can replicate your results. For it to be
/open/, the materials (code, data and sufficient documentation) need to be
available for others. Simply dumping all of your code into something like GitHub
is not sufficient for your research to be considered reproducible.

** Git

Created in 2005 by Linus Torvalds to help with the development of the Linux
kernel, git has become a fundamental tool in software development. In the 2021
Stackoverflow Developer Survey over \(90\%\) of respondents used git; it is
nearly synonymous with version control. If you intend to collaborate in the
writing of substantial amounts of code, taking the time to learn how to use git
is a good idea.

Working through the practical example below will be much easier if we get
familiar with some of the git terminology first. Unless you are familiar with
git already, you should at least skim these before continuing.

*** Repository

A /repository/ is a directory containing your files and the history of all the
edits (see [[*Commit][commit]]) made to these files. You can have a repository that only
lives on your machine, but they are often shared on a platform such as GitHub.

*** Commit

An edit to a file that you have recorded as part of the history of edits is
called a /commit/. It is both a noun and a verb, you commit an edit and the
[[*Repository][repository]] contains all of your commits. This can be thought of as a stronger
version of saving a file.

*** Clone

When you make a copy of a [[*Repository][repository]] you are /cloning/ that repository. The
resulting copy is referred to as a /clone/. Typically this will mean you have
downloaded a copy from a platform such as GitHub.

*** Pull

Suppose you [[*Clone][cloned]] a repository a while ago and you want to get a copy of all
the [[*Commit][commits]] that have been made to the original repository since then. To get
these commits you /pull/ them, which is a fancy way of saying updating your files.
This is sometimes referred to as /fetching/.

*** Push

If you have [[*Commit][commited]] some changes to your [[*Clone][clone]] of a [[*Repository][repository]] and want the
original repository to have these changes made, you /push/ these changes. This is
a fancy way of saying use your edits to update the original files.

*** Branch (beyond scope)

A /branch/ is similar to a [[*Clone][clone]] in that it is a copy of a [[*Repository][repository]]. This
provides a more sophisticated way for people to work on their own version of
code, without messing up the main copy. This is not particularly important
unless you are collaborating with others on a project.

*** Merge (beyond scope)

If someone has made some useful changes on their [[*Branch (beyond scope)][branch]], the owner of the
repository may decide to include their commits in the main copy. This process of
including the changes on someone's branch is called /merging/ the changes.

*** Fork (beyond scope)

When you make a copy of a repository that sits on your GitHub account. This is
similar to, but distinct from [[*Clone][cloning]] and making a [[*Branch][branch]].

** GitHub

*** What is GitHub?

GitHub, Inc. is a subsidairy of Microsoft. Their website provides freemium
hosting of git repositories. In addition to hosting the repositories, it offers
additional tools to assist with software development. We will make extensive use
of GitHub in this tutorial to avoid you needing to install anything on your
machine. If you are going to use git extensively, it would be wise to learn how
to do this from the command line or some other program.

*** Setting up a GitHub account

To register an account you will need an email address that can be used for
verification.

1. Visit [[https://github.com/]] and click *Sign Up*.
2. Fill in the forms to create an account.
3. Verify that account by entering the access code GitHub sends to the email
   address you registered with.
4. Verify that you can summon the *Command Palette* with =crtl k= for Windows and
   Linux and =command k= on a mac.
5. The appearance and accessibility settings can be reached by searching for
   them in the command palette.

** TODO Zenodo

* TODO Worked example

- You start with some code that generates the pictures needed for a manuscript.
  + Start with some dummy data and a single figure that can be put into a dummy document
  + There is a data file and a final figure and a script that makes for later from the former using R.
  + You want to put that onto github so that others can use it, you want others to be able to build off of it
- You start by setting up the materials in a way that are good for this purpose.
  + You need to put a license on this
  + You need to put a readme so people know what it is all about
  + You need to have a sensible layout of the materials
  + You need to record the environment you used to carry out the computation in case someone wants to recreate it exactly
- You make a github account and repository
  + You need to set up an account
  + You need to set up all the access for your machine
  + You make a repository
- You upload it all to github
  + You need to make a copy of this on your machine
  + You need to move all of your materials into that reposotiry
  + You need to push the changes to github
- You get told you need to change something so you do that
  + You need to make a change and push that change
- You might want to archive this on zenodo or something similar

* TODO Next steps and alternative solutions

- You need to know where you can learn more about git
- You need to know what tools are used for what purposes
- You need to know how to navigate github including the issue tracker and assess liveliness

* TODO Homework

** Question 1

- Explain (in 100--200 words) the purpose of git, github, and zenodo and the
  relationship between these things.
- Find and report an alternative to each of these tools (50--150 words).

** Question 2

- Explain (in 100--200 words) the role of version control in reproducible
  research.
- Give an example (in 100--150 words) of a situation in which version control
  does not suffice to make a piece of work reproducible.

** Question 3

- Download the following script and data and organise this material in a
  repository in a suitable way.
- Give a brief overview of the decisions you made along the way (100--200
  words).

** TODO Question 4

- Fork the repository at *XXX* and merge the pull request. Note that this will
  require resolving conflicts in a sensible way.
- Give a brief overview of the decisions you made along the way (100--150
  words).

** Question 5

- Read the editorial [[https://doi.org/10.1371/journal.pcbi.1003285][Ten Simple Rules for Reproducible Computational Research]]
  and (in 200--300 words) give a brief explanation of how git and GitHub would
  or would not be relevant to each rule.
